import { VolunteerOpportunity } from "./types";

export const volunteerOpportunities: VolunteerOpportunity[] = [
  {
    id: 1,
    title: "Teach English to Children",
    organization: "Austin Community Outreach",
    location: {
      address: "Springdale Elementary School, Austin, TX",
      pincode: "78721",
      latitude: 30.2832,
      longitude: -97.6866,
    },
    description:
      "Volunteer to teach English to underprivileged children at Springdale Elementary School.",
    start_date: "2024-10-25",
    end_date: "2024-11-15",
    contact_info: "contact@austinoutreach.org",
    categories: ["education", "children"],
  },
  {
    id: 2,
    title: "Park Cleanup Volunteer",
    organization: "Austin Parks and Rec",
    location: {
      address: "Zilker Park, Austin, TX",
      pincode: "78704",
      latitude: 30.2669,
      longitude: -97.7724,
    },
    description:
      "Help clean and maintain the beautiful Zilker Park. Volunteers will be provided with equipment.",
    start_date: "2024-10-28",
    end_date: "2024-11-10",
    contact_info: "cleanup@austinparks.org",
    categories: ["environment", "community"],
  },
  {
    id: 3,
    title: "Food Bank Volunteer",
    organization: "Central Texas Food Bank",
    location: {
      address: "6500 Metropolis Dr, Austin, TX",
      pincode: "78744",
      latitude: 30.1896,
      longitude: -97.7411,
    },
    description:
      "Help sort and pack food items for distribution to families in need.",
    start_date: "2024-11-01",
    end_date: "2024-11-30",
    contact_info: "volunteer@centraltexasfoodbank.org",
    categories: ["hunger", "community"],
  },
  {
    id: 4,
    title: "Animal Shelter Volunteer",
    organization: "Austin Pets Alive!",
    location: {
      address: "1156 W Cesar Chavez St, Austin, TX",
      pincode: "78703",
      latitude: 30.2691,
      longitude: -97.7624,
    },
    description:
      "Volunteer at the Austin Pets Alive! shelter to care for animals and assist with adoption events.",
    start_date: "2024-10-27",
    end_date: "2024-12-01",
    contact_info: "volunteer@austinpetsalive.org",
    categories: ["animal welfare", "community"],
  },
  {
    id: 5,
    title: "Community Garden Volunteer",
    organization: "Austin Urban Gardens",
    location: {
      address: "700 W 4th St, Austin, TX",
      pincode: "78701",
      latitude: 30.2663,
      longitude: -97.7473,
    },
    description:
      "Help maintain a local community garden by planting, weeding, and watering.",
    start_date: "2024-10-29",
    end_date: "2024-11-20",
    contact_info: "volunteer@austingardens.org",
    categories: ["environment", "community"],
  },
  {
    id: 6,
    title: "Senior Care Volunteer",
    organization: "Golden Years Senior Center",
    location: {
      address: "5805 Shoal Creek Blvd, Austin, TX",
      pincode: "78757",
      latitude: 30.3499,
      longitude: -97.7427,
    },
    description:
      "Spend time with seniors, helping with activities, meals, and companionship.",
    start_date: "2024-11-05",
    end_date: "2024-12-15",
    contact_info: "info@goldenyears.org",
    categories: ["elderly care", "community"],
  },
  {
    id: 7,
    title: "Library Assistant Volunteer",
    organization: "Austin Public Library",
    location: {
      address: "710 W Cesar Chavez St, Austin, TX",
      pincode: "78701",
      latitude: 30.2634,
      longitude: -97.7486,
    },
    description:
      "Assist library staff with organizing books and setting up for reading programs.",
    start_date: "2024-10-30",
    end_date: "2024-11-25",
    contact_info: "volunteer@austinlibrary.org",
    categories: ["education", "community"],
  },
  {
    id: 8,
    title: "Mental Health Awareness Volunteer",
    organization: "Austin Mental Health Foundation",
    location: {
      address: "1212 W 6th St, Austin, TX",
      pincode: "78703",
      latitude: 30.2733,
      longitude: -97.7625,
    },
    description:
      "Help raise awareness about mental health resources and assist in organizing community outreach events.",
    start_date: "2024-11-01",
    end_date: "2024-11-30",
    contact_info: "info@mentalhealthaustin.org",
    categories: ["health", "community"],
  },
  {
    id: 9,
    title: "Wildlife Conservation Volunteer",
    organization: "Austin Wildlife Rescue",
    location: {
      address: "5401 E MLK Blvd, Austin, TX",
      pincode: "78721",
      latitude: 30.2839,
      longitude: -97.6769,
    },
    description:
      "Assist in caring for injured wildlife and help in rehabilitation efforts.",
    start_date: "2024-11-02",
    end_date: "2024-12-01",
    contact_info: "volunteer@austinwildliferescue.org",
    categories: ["animal welfare", "environment"],
  },
  {
    id: 10,
    title: "Job Skills Training Volunteer",
    organization: "Austin Career Services",
    location: {
      address: "2500 E 6th St, Austin, TX",
      pincode: "78702",
      latitude: 30.2595,
      longitude: -97.7209,
    },
    description:
      "Provide job skills training, including resume building and interview techniques, to underserved individuals.",
    start_date: "2024-11-05",
    end_date: "2024-12-10",
    contact_info: "contact@austincareerservices.org",
    categories: ["employment", "community"],
  },
  {
    id: 11,
    title: "STEM Program Volunteer",
    organization: "Tech Innovators Group",
    location: {
      address: "3224 Highland Terrace, Springdale, Austin, TX",
      pincode: "78721",
      latitude: 30.2832,
      longitude: -97.6866,
    },
    description:
      "Help students explore STEM subjects through hands-on activities and experiments.",
    start_date: "2024-11-01",
    end_date: "2024-12-15",
    contact_info: "contact@techinnovators.org",
    categories: ["youth", "education"],
  },
  {
    id: 12,
    title: "Food Bank Volunteer",
    organization: "Austin Community Pantry",
    location: {
      address: "1732 Zilker Park Blvd, Austin, TX",
      pincode: "78704",
      latitude: 30.2669,
      longitude: -97.7724,
    },
    description:
      "Assist in sorting and distributing food to families in need in the community.",
    start_date: "2024-10-28",
    end_date: "2024-12-30",
    contact_info: "volunteer@austinpantry.org",
    categories: ["community", "health"],
  },
  {
    id: 13,
    title: "Pet Adoption Assistant",
    organization: "Happy Paws Animal Shelter",
    location: {
      address: "7603 Metropolis Dr, Austin, TX",
      pincode: "78744",
      latitude: 30.1896,
      longitude: -97.7411,
    },
    description:
      "Help match potential adopters with rescue pets and facilitate the adoption process.",
    start_date: "2024-11-05",
    end_date: "2025-01-20",
    contact_info: "volunteer@happypaws.org",
    categories: ["animal welfare"],
  },
  {
    id: 14,
    title: "Art Workshop Assistant",
    organization: "Creative Spaces Austin",
    location: {
      address: "4301 Cesar Chavez St, Austin, TX",
      pincode: "78703",
      latitude: 30.2691,
      longitude: -97.7624,
    },
    description:
      "Assist local artists in conducting art workshops for children and adults.",
    start_date: "2024-11-15",
    end_date: "2025-01-05",
    contact_info: "volunteer@creativespaces.org",
    categories: ["arts", "community"],
  },
  {
    id: 15,
    title: "Wildlife Conservation",
    organization: "EcoFriends Texas",
    location: {
      address: "1021 Downtown Blvd, Austin, TX",
      pincode: "78701",
      latitude: 30.2663,
      longitude: -97.7473,
    },
    description:
      "Participate in wildlife conservation efforts to protect endangered species in local parks.",
    start_date: "2024-11-10",
    end_date: "2024-12-30",
    contact_info: "volunteer@ecofriends.org",
    categories: ["environment"],
  },
  {
    id: 16,
    title: "Mental Health Awareness Campaign",
    organization: "Wellness for All",
    location: {
      address: "5921 Shoal Creek Blvd, Austin, TX",
      pincode: "78757",
      latitude: 30.3499,
      longitude: -97.7427,
    },
    description:
      "Support the coordination of mental health awareness events and outreach campaigns.",
    start_date: "2024-10-29",
    end_date: "2024-12-25",
    contact_info: "volunteer@wellnessforall.org",
    categories: ["health"],
  },
  {
    id: 17,
    title: "Youth Group Leader",
    organization: "Austin Youth Network",
    location: {
      address: "2101 East Austin Blvd, Austin, TX",
      pincode: "78702",
      latitude: 30.2595,
      longitude: -97.7209,
    },
    description:
      "Lead a youth group and mentor students in various personal and academic projects.",
    start_date: "2024-11-02",
    end_date: "2025-01-31",
    contact_info: "volunteer@youthnetwork.org",
    categories: ["youth", "education"],
  },
  {
    id: 18,
    title: "Tree Planting Event",
    organization: "Green Austin",
    location: {
      address: "4821 Pleasant Valley Dr, Austin, TX",
      pincode: "78741",
      latitude: 30.2326,
      longitude: -97.7151,
    },
    description:
      "Join our tree-planting drive to help increase green spaces in the city.",
    start_date: "2024-11-12",
    end_date: "2024-12-15",
    contact_info: "volunteer@greenaustin.org",
    categories: ["environment"],
  },
  {
    id: 19,
    title: "Hospital Assistant",
    organization: "Austin Medical Center",
    location: {
      address: "3601 Southpark Meadows Dr, Austin, TX",
      pincode: "78748",
      latitude: 30.1722,
      longitude: -97.8285,
    },
    description:
      "Help medical staff with administrative duties and provide assistance to patients.",
    start_date: "2024-11-03",
    end_date: "2025-01-31",
    contact_info: "volunteer@amc.org",
    categories: ["health"],
  },
  {
    id: 20,
    title: "Resume Building Workshop",
    organization: "Career Mentors Austin",
    location: {
      address: "3420 University Dr, UT Area, Austin, TX",
      pincode: "78705",
      latitude: 30.2935,
      longitude: -97.7383,
    },
    description:
      "Help job seekers improve their resumes and prepare for employment opportunities.",
    start_date: "2024-11-01",
    end_date: "2024-12-10",
    contact_info: "volunteer@careermentors.org",
    categories: ["employment"],
  },
  {
    id: 21,
    title: "Soup Kitchen Helper",
    organization: "Austin Homeless Assistance",
    location: {
      address: "1234 Main St, Austin, TX",
      pincode: "78701",
      latitude: 30.2711,
      longitude: -97.7437,
    },
    description:
      "Help serve meals to homeless individuals and families at our downtown soup kitchen.",
    start_date: "2024-11-05",
    end_date: "2025-01-15",
    contact_info: "volunteer@austinassist.org",
    categories: ["community", "hunger"],
  },
  {
    id: 22,
    title: "Homeless Shelter Support Volunteer",
    organization: "Austin Shelter Aid",
    location: {
      address: "1342 Guadalupe St, Austin, TX",
      pincode: "78701",
      latitude: 30.2746,
      longitude: -97.7425,
    },
    description:
      "Provide administrative support and help organize donation drives for the homeless shelter.",
    start_date: "2024-11-10",
    end_date: "2025-02-20",
    contact_info: "volunteer@austinshelter.org",
    categories: ["community", "housing"],
  },
  {
    id: 23,
    title: "Homework Tutor for At-Risk Youth",
    organization: "Austin Youth Academy",
    location: {
      address: "600 East 6th St, Austin, TX",
      pincode: "78701",
      latitude: 30.2675,
      longitude: -97.7397,
    },
    description:
      "Provide after-school homework assistance to students from low-income families.",
    start_date: "2024-11-08",
    end_date: "2024-12-20",
    contact_info: "tutor@austinyouth.org",
    categories: ["education", "youth"],
  },
  {
    id: 24,
    title: "Clothing Donation Center Volunteer",
    organization: "Austin Clothing Bank",
    location: {
      address: "2901 Guadalupe St, Austin, TX",
      pincode: "78705",
      latitude: 30.2931,
      longitude: -97.7382,
    },
    description: "Sort and distribute donated clothing items to those in need.",
    start_date: "2024-11-03",
    end_date: "2025-01-31",
    contact_info: "volunteer@austinclothingbank.org",
    categories: ["community", "clothing"],
  },
  {
    id: 25,
    title: "Legal Aid Clinic Volunteer",
    organization: "Austin Legal Aid",
    location: {
      address: "201 Lavaca St, Austin, TX",
      pincode: "78701",
      latitude: 30.2652,
      longitude: -97.7471,
    },
    description:
      "Assist attorneys in providing free legal advice and services to low-income individuals.",
    start_date: "2024-11-10",
    end_date: "2025-02-25",
    contact_info: "volunteer@austinlegalaid.org",
    categories: ["legal aid", "community"],
  },
  {
    id: 26,
    title: "Digital Literacy Teacher for Seniors",
    organization: "Austin Digital Literacy Project",
    location: {
      address: "1222 North Lamar Blvd, Austin, TX",
      pincode: "78703",
      latitude: 30.2719,
      longitude: -97.7514,
    },
    description: "Teach basic computer and internet skills to senior citizens.",
    start_date: "2024-11-15",
    end_date: "2025-01-20",
    contact_info: "teach@digitalaustin.org",
    categories: ["technology", "elderly care"],
  },
  {
    id: 27,
    title: "Nature Walk Guide",
    organization: "Austin Nature Center",
    location: {
      address: "301 Nature Dr, Austin, TX",
      pincode: "78746",
      latitude: 30.2793,
      longitude: -97.8024,
    },
    description:
      "Lead educational nature walks for school groups and the general public.",
    start_date: "2024-11-04",
    end_date: "2025-03-15",
    contact_info: "nature@austinnature.org",
    categories: ["environment", "education"],
  },
  {
    id: 28,
    title: "Refugee Support Volunteer",
    organization: "Austin Refugee Aid",
    location: {
      address: "345 International Dr, Austin, TX",
      pincode: "78741",
      latitude: 30.2271,
      longitude: -97.7168,
    },
    description:
      "Help newly arrived refugee families with settling in and accessing community resources.",
    start_date: "2024-11-10",
    end_date: "2025-02-20",
    contact_info: "volunteer@austinrefugeeaid.org",
    categories: ["community", "refugee assistance"],
  },
  {
    id: 29,
    title: "Bike Repair Workshop Volunteer",
    organization: "Austin Bicycle Collective",
    location: {
      address: "1001 East 5th St, Austin, TX",
      pincode: "78702",
      latitude: 30.2625,
      longitude: -97.7339,
    },
    description:
      "Help repair bicycles for low-income individuals and teach basic bike maintenance.",
    start_date: "2024-11-06",
    end_date: "2025-01-30",
    contact_info: "volunteer@austinbike.org",
    categories: ["community", "transportation"],
  },
  {
    id: 30,
    title: "Disaster Relief Volunteer",
    organization: "Austin Disaster Recovery Team",
    location: {
      address: "789 Emergency St, Austin, TX",
      pincode: "78741",
      latitude: 30.2311,
      longitude: -97.7153,
    },
    description:
      "Help in disaster recovery efforts by distributing supplies and assisting affected families.",
    start_date: "2024-11-15",
    end_date: "2025-03-01",
    contact_info: "disaster@austindisaster.org",
    categories: ["community", "disaster relief"],
  },
  {
    id: 31,
    title: "Urban Wildlife Rescue Volunteer",
    organization: "Austin Wildlife Project",
    location: {
      address: "502 West Ave, Austin, TX",
      pincode: "78701",
      latitude: 30.2708,
      longitude: -97.7493,
    },
    description:
      "Assist in rescuing and rehabilitating injured urban wildlife.",
    start_date: "2024-11-12",
    end_date: "2025-02-28",
    contact_info: "wildlife@austinwild.org",
    categories: ["animal welfare", "environment"],
  },
  {
    id: 32,
    title: "Local Farmers Market Volunteer",
    organization: "Austin Farmers Alliance",
    location: {
      address: "789 Farmers Ln, Austin, TX",
      pincode: "78704",
      latitude: 30.2471,
      longitude: -97.7529,
    },
    description:
      "Help organize and assist vendors at the weekly farmers market.",
    start_date: "2024-11-01",
    end_date: "2025-01-15",
    contact_info: "volunteer@austinfarmers.org",
    categories: ["community", "agriculture"],
  },
  {
    id: 33,
    title: "Youth Robotics Coach",
    organization: "Austin Robotics Club",
    location: {
      address: "4001 North Lamar Blvd, Austin, TX",
      pincode: "78756",
      latitude: 30.3123,
      longitude: -97.7314,
    },
    description:
      "Coach middle and high school students in building and programming robots for competitions.",
    start_date: "2024-11-05",
    end_date: "2025-02-10",
    contact_info: "robotics@austinclub.org",
    categories: ["education", "technology"],
  },
  {
    id: 34,
    title: "Job Interview Preparation",
    organization: "Career Development Center",
    location: {
      address: "1234 Main St, Suite 100, Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Prepare for job interviews with mock interviews and feedback.",
    start_date: "2024-11-15",
    end_date: "2024-11-30",
    contact_info: "info@cdc.org",
    categories: ["employment", "workshops"],
  },
  {
    id: 35,
    title: "Networking Event",
    organization: "Austin Networking Group",
    location: {
      address: "5678 Burnet Rd, Austin, TX",
      pincode: "78757",
      latitude: 30.3141,
      longitude: -97.7071,
    },
    description: "Connect with local professionals and expand your network.",
    start_date: "2024-12-05",
    end_date: "2024-12-05",
    contact_info: "connect@austinnetworking.org",
    categories: ["networking", "employment"],
  },
  {
    id: 36,
    title: "Career Fair",
    organization: "Austin Job Fair",
    location: {
      address: "Austin Convention Center, 500 E Cesar Chavez St, Austin, TX",
      pincode: "78701",
      latitude: 30.2633,
      longitude: -97.7364,
    },
    description:
      "Meet with potential employers and learn about job opportunities.",
    start_date: "2024-11-20",
    end_date: "2024-11-20",
    contact_info: "jobs@austinjobs.com",
    categories: ["employment", "career fairs"],
  },
  {
    id: 37,
    title: "STEM Tutor",
    organization: "Austin STEM Alliance",
    location: {
      address: "1234 Main St, Austin, TX",
      pincode: "78701",
      latitude: 30.2711,
      longitude: -97.7437,
    },
    description:
      "Mentor students in math, science, technology, or engineering.",
    start_date: "2024-11-05",
    end_date: "2025-01-15",
    contact_info: "stem@austinSTEM.org",
    categories: ["education", "youth"],
  },
  {
    id: 38,
    title: "Volunteer at Austin Animal Shelter",
    organization: "Austin Animal Shelter",
    location: {
      address: "7201 Levander Loop, Austin, TX",
      pincode: "78702",
      latitude: 30.2573,
      longitude: -97.6948,
    },
    description: "Assist in caring for animals and help with adoption events.",
    start_date: "2024-11-01",
    end_date: "2025-01-31",
    contact_info: "volunteer@austinanimal.org",
    categories: ["animal welfare", "community"],
  },
  {
    id: 39,
    title: "Build Homes with Austin Habitat for Humanity",
    organization: "Austin Habitat for Humanity",
    location: {
      address: "500 West 15th St, Austin, TX",
      pincode: "78701",
      latitude: 30.2705,
      longitude: -97.7476,
    },
    description: "Help build homes for low-income families in the community.",
    start_date: "2024-11-10",
    end_date: "2025-02-20",
    contact_info: "build@austinhabitat.org",
    categories: ["housing", "community"],
  },
  {
    id: 40,
    title: "Sort Food Donations at Austin Food Bank",
    organization: "Austin Food Bank",
    location: {
      address: "6500 Metropolis Dr, Austin, TX",
      pincode: "78744",
      latitude: 30.2295,
      longitude: -97.6827,
    },
    description: "Help sort and package food donations for distribution.",
    start_date: "2024-11-02",
    end_date: "2025-01-15",
    contact_info: "volunteer@austinfoodbank.org",
    categories: ["hunger", "community"],
  },
  {
    id: 41,
    title: "Join Austin Community Gardens",
    organization: "Austin Community Gardens",
    location: {
      address: "6001 Waller Creek Dr, Austin, TX",
      pincode: "78757",
      latitude: 30.3137,
      longitude: -97.6964,
    },
    description:
      "Assist in maintaining community gardens and promote sustainable practices.",
    start_date: "2024-11-12",
    end_date: "2025-03-01",
    contact_info: "info@austincommunitygardens.org",
    categories: ["environment", "community"],
  },
  {
    id: 42,
    title: "Tutor Adults at Austin Literacy Coalition",
    organization: "Austin Literacy Coalition",
    location: {
      address: "2504 Lareina Dr, Austin, TX",
      pincode: "78704",
      latitude: 30.2482,
      longitude: -97.7584,
    },
    description:
      "Provide one-on-one tutoring to adults seeking to improve their literacy skills.",
    start_date: "2024-11-15",
    end_date: "2025-01-30",
    contact_info: "tutor@austinliteracy.org",
    categories: ["education", "community"],
  },
  {
    id: 43,
    title: "Support Austin Youth Theater",
    organization: "Austin Youth Theater",
    location: {
      address: "1300 West 15th St, Austin, TX",
      pincode: "78703",
      latitude: 30.2753,
      longitude: -97.7516,
    },
    description:
      "Help with stage production and coaching for youth theater performances.",
    start_date: "2024-11-08",
    end_date: "2025-02-05",
    contact_info: "info@austinyouththeater.org",
    categories: ["education", "arts"],
  },
  {
    id: 44,
    title: "Assist at Austin Community Center",
    organization: "Austin Community Center",
    location: {
      address: "201 East 24th St, Austin, TX",
      pincode: "78705",
      latitude: 30.2841,
      longitude: -97.7341,
    },
    description:
      "Assist in organizing community events and activities for residents.",
    start_date: "2024-11-07",
    end_date: "2025-01-15",
    contact_info: "events@austincommunitycenter.org",
    categories: ["community", "events"],
  },
  {
    id: 45,
    title: "Help Austin Homeless Outreach",
    organization: "Austin Homeless Outreach",
    location: {
      address: "2222 West 6th St, Austin, TX",
      pincode: "78703",
      latitude: 30.2769,
      longitude: -97.7503,
    },
    description:
      "Provide food and hygiene products to homeless individuals in the area.",
    start_date: "2024-11-10",
    end_date: "2025-01-20",
    contact_info: "outreach@austinoutreach.org",
    categories: ["hunger", "community"],
  },
  {
    id: 46,
    title: "Volunteer at Austin Senior Center",
    organization: "Austin Senior Center",
    location: {
      address: "919 W 28th St, Austin, TX",
      pincode: "78705",
      latitude: 30.2848,
      longitude: -97.7483,
    },
    description:
      "Assist with activities and events for senior citizens in the community.",
    start_date: "2024-11-01",
    end_date: "2025-01-31",
    contact_info: "volunteer@austinseniorcenter.org",
    categories: ["elderly care", "community"],
  },
  {
    id: 47,
    title: "Participate in Austin Environmental Initiative",
    organization: "Austin Environmental Initiative",
    location: {
      address: "400 East 15th St, Austin, TX",
      pincode: "78701",
      latitude: 30.2694,
      longitude: -97.7371,
    },
    description:
      "Participate in local environmental cleanup efforts and conservation projects.",
    start_date: "2024-11-05",
    end_date: "2025-03-05",
    contact_info: "cleanup@austinenviro.org",
    categories: ["environment", "community"],
  },
  {
    id: 48,
    title: "Coach Youth Sports in Austin",
    organization: "Austin Youth Sports",
    location: {
      address: "900 East 30th St, Austin, TX",
      pincode: "78705",
      latitude: 30.2969,
      longitude: -97.7241,
    },
    description:
      "Coach youth sports teams and help promote healthy lifestyles.",
    start_date: "2024-11-03",
    end_date: "2025-02-28",
    contact_info: "coach@austinyouthsports.org",
    categories: ["sports", "youth"],
  },
  {
    id: 49,
    title: "Music Instructor and Community Event Organizer",
    organization: "Austin Music Project",
    location: {
      address: "303 West 8th St, Austin, TX",
      pincode: "78701",
      latitude: 30.2649,
      longitude: -97.7435,
    },
    description:
      "Teach music lessons and help organize community music events.",
    start_date: "2024-11-14",
    end_date: "2025-03-01",
    contact_info: "music@austinmusicproject.org",
    categories: ["arts", "education"],
  },
  {
    id: 50,
    title: "Park Maintenance and Improvement Volunteer",
    organization: "Austin Green Space Coalition",
    location: {
      address: "812 East 12th St, Austin, TX",
      pincode: "78702",
      latitude: 30.2632,
      longitude: -97.7251,
    },
    description:
      "Assist in the maintenance and improvement of local parks and green spaces.",
    start_date: "2024-11-09",
    end_date: "2025-02-09",
    contact_info: "greenspace@austingreens.org",
    categories: ["environment", "community"],
  },
  {
    id: 51,
    title: "Academic Coach for First-Generation Students",
    organization: "Breakthrough Central Texas",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Create paths to college for first-generation students as an academic coach, after-school tutor, or application coach.",
    start_date: "2024-11-01",
    end_date: "2025-01-31",
    contact_info: "info@breakthroughctx.org",
    categories: ["education", "youth"],
  },
  {
    id: 52,
    title: "Event Assistant and Counselor for Sickle Cell Patients",
    organization: "Sickle Cell Association of Texas",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Provide holistic care for those affected by sickle cell disease through event assistance and counseling at Camp Cell-A-Bration.",
    start_date: "2024-11-15",
    end_date: "2025-01-30",
    contact_info: "volunteer@sicklecelltx.org",
    categories: ["health", "community"],
  },
  {
    id: 53,
    title: "Youth Tutor and Career Mentor",
    organization: "American YouthWorks",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Volunteer for tutoring, career mentoring, and hands-on projects for youth.",
    start_date: "2024-11-10",
    end_date: "2025-02-20",
    contact_info: "volunteer@americanyouthworks.org",
    categories: ["education", "youth"],
  },
  {
    id: 54,
    title: "Media and Technology Instructor for Young Girls",
    organization: "Latinitas",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Empower young girls through media and technology; seek volunteers for instructional roles and guest speaking.",
    start_date: "2024-11-05",
    end_date: "2025-03-05",
    contact_info: "info@latinitasmagazine.org",
    categories: ["education", "youth"],
  },
  {
    id: 55,
    title: "Team Coach and Event Volunteer",
    organization: "Girls on the Run",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Inspire girls through running and life skills; volunteers can coach teams or assist with events.",
    start_date: "2024-11-08",
    end_date: "2025-02-28",
    contact_info: "info@gotraustin.org",
    categories: ["education", "sports"],
  },
  {
    id: 56,
    title: "Youth and Family Support Volunteer",
    organization: "LifeWorks",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Help youth and families achieve self-sufficiency through group projects or events.",
    start_date: "2024-11-12",
    end_date: "2025-01-15",
    contact_info: "volunteer@lifeworksaustin.org",
    categories: ["community", "youth"],
  },
  {
    id: 57,
    organization: "Hoofbeats Academy",
    title: "Equine Therapy Assistant",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Assist with equine therapy for differently-abled students; help with horse riding lessons and facility maintenance.",
    start_date: "2024-11-03",
    end_date: "2025-02-28",
    contact_info: "info@hoofbeatsacademy.org",
    categories: ["therapy", "community"],
  },
  {
    id: 58,
    title: "Book Sorting and Cleaning Volunteer",
    organization: "Texas Kids Read",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Provide free books to children in Title 1 schools; help sort and clean donated books.",
    start_date: "2024-11-01",
    end_date: "2025-01-31",
    contact_info: "info@txkidsread.org",
    categories: ["education", "community"],
  },
  {
    id: 59,
    title: "Creative Writing Workshop Assistant",
    organization: "Austin Bat Cave",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Assist with creative writing workshops and tutoring for students.",
    start_date: "2024-11-14",
    end_date: "2025-03-01",
    contact_info: "volunteer@austinbatcave.org",
    categories: ["education", "arts"],
  },
  {
    id: 60,
    title: "Youth Development Coach and Administrative Support",
    organization: "YMCA of Austin",
    location: {
      address: "Austin, TX",
      pincode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    description:
      "Focus on youth development and healthy living; volunteer as a coach or administrative support.",
    start_date: "2024-11-01",
    end_date: "2025-01-31",
    contact_info: "volunteer@ymcaustin.org",
    categories: ["sports", "community"],
  },
];

export function getUniqueCategories(
  opportunities: VolunteerOpportunity[]
): string[] {
  const allCategories = opportunities.flatMap(
    (opportunity) => opportunity.categories
  );
  const uniqueCategories = Array.from(new Set(allCategories));
  return uniqueCategories;
}
export function getUniquePincodes(
  opportunities: VolunteerOpportunity[]
): string[] {
  const allPincodes = opportunities.flatMap(
    (opportunity) => opportunity.location.pincode
  );
  const uniquePincodes = Array.from(new Set(allPincodes));
  return uniquePincodes;
}
